### ISSUE TITLE
There are no reachable cache hosts available. Verify your client settings and ensure that all cache hosts can be successfully communicated with from this client

### ISSUE THREAD

**Issue by Mds92** [ironyx/dache#33]
After updating to last version I receive the following exception from clients:

<b>There are no reachable cache hosts available. Verify your client settings and ensure that all cache hosts can be successfully communicated with from this client</b>

Client config:

<pre>&lt;configSections&gt;
    &lt;section name=&quot;cacheClientSettings&quot; type=&quot;Dache.Client.Configuration.CacheClientConfigurationSection, Dache.Client&quot; /&gt;          
    &lt;/sectionGroup&gt;
    &lt;section name=&quot;resizer&quot; type=&quot;ImageResizer.ResizerSection&quot; requirePermission=&quot;false&quot; /&gt;
  &lt;/configSections&gt;
  &lt;cacheClientSettings hostReconnectIntervalSeconds=&quot;10&quot; hostRedundancyLayers=&quot;0&quot;&gt;
    &lt;cacheHosts&gt;
      &lt;add address=&quot;localhost&quot; port=&quot;33333&quot; /&gt;
    &lt;/cacheHosts&gt;
  &lt;/cacheClientSettings&gt;</pre>

I've hosted the dache host on windows service, with the following config:
<pre>&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;configuration&gt;
  &lt;configSections&gt;
    &lt;section name=&quot;cacheHostSettings&quot; type=&quot;Dache.CacheHost.Configuration.CacheHostConfigurationSection, Dache.CacheHost&quot; allowExeDefinition=&quot;MachineToApplication&quot; /&gt;
  &lt;/configSections&gt;
  &lt;startup&gt;
    &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.5&quot; /&gt;
  &lt;/startup&gt;
  &lt;cacheHostSettings maximumConnections=&quot;40&quot; cacheMemoryLimitPercentage=&quot;85&quot; port=&quot;33333&quot; /&gt;
&lt;/configuration&gt;
</pre>

It worked well, but after updating the error has occurred !<br />
I'm dead sure the windows service (dache host) is running.

**Comment by Mds92** [comment]
I've checked the dache cache host log:

<pre>2015-01-17T22:40:47 WARN Dache Client Disconnected : System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at SimplSockets.SimplSocketServer.KeepAlive(Socket socket) in d:\SimplSockets\SimplSockets\SimplSocketServer.cs:line 418</pre>

Is it helpful ?

**Comment by ironyx** [comment]
Interesting. Can you reliably reproduce this issue or does stopping and starting the service/client fix it?

**Comment by Mds92** [comment]
I've stopped and started the service multiple,
I can stop and start DacheHost service without any problems,  but the exception occurred again.

**Comment by ironyx** [comment]
@Mds92 are you certain you're running the very latest version? 1.5.5

**Comment by Mds92** [comment]
Yes, I'm dead sure.
What about maximum data volume. Is possible the problem related to it?
Should I change it?

**Comment by ironyx** [comment]
Does the problem happen at random, or when using Dache? Trying for a repro so I can fix it.

**Comment by ironyx** [comment]
How much data are you sending at once? It's possible you're surpassing the limit?

**Comment by ironyx** [comment]
@Mds92 try cranking up `maximumMessageSizeKB`, default is 10MB. See documentation here:

https://github.com/ironyx/dache/wiki/Configuration-Settings

**Comment by Mds92** [comment]
The problem was solved
I change maximumMessageSizeKB to 2GB, and it worked without any problems :-)
Is it OK to set `maximumMessageSizeKB` to 2GB?

**Comment by ironyx** [comment]
Glad that it is solved. It is OK to set the max to a high value!

I am very curious - are you using the bulk API a ton? What's your throughput (how many adds/gets/whatever per second)?

**Comment by Mds92** [comment]
I checked my data volume. it was around 11MB, 
In previous version it didn't have a problem, but in this version that you fixed `maximumMessageSizeKB` to 10 MB the exception occurred.

I set `maximumMessageSizeKB` to 2GB for max reliability to prevent another exception :-)
Thanks anyway

**Comment by ironyx** [comment]
Makes sense. Glad it's resolved! I should probably make the max size exceeded error be more visible in a future version.
