### ISSUE TITLE
Dache cache host, stuck at most of the times ?

### ISSUE THREAD

**Issue by Mds92** [ironyx/dache#34]
I'm working with latest version 1.5.5 of dache.net
I hosted it on Windows Services with the following config:

<pre>&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;configuration&gt;
  &lt;configSections&gt;
        &lt;section name=&quot;cacheHostSettings&quot; type=&quot;Dache.CacheHost.Configuration.CacheHostConfigurationSection, Dache.CacheHost&quot; allowExeDefinition=&quot;MachineToApplication&quot; /&gt;
    &lt;/configSections&gt;
  &lt;startup&gt;
    &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.5&quot; /&gt;
  &lt;/startup&gt;
  &lt;cacheHostSettings maximumConnections=&quot;40&quot; cacheMemoryLimitPercentage=&quot;85&quot; maximumMessageSizeKB=&quot;2097151&quot; port=&quot;33333&quot; /&gt;
&lt;/configuration&gt;</pre>

In clients I have the following config:

<pre><configSections>
    .
	.
	.
    &lt;section name=&quot;cacheClientSettings&quot; type=&quot;Dache.Client.Configuration.CacheClientConfigurationSection, Dache.Client&quot; /&gt;
    .
	.
	.
  &lt;/configSections&gt;
  &lt;cacheClientSettings hostReconnectIntervalSeconds=&quot;10&quot; hostRedundancyLayers=&quot;0&quot; maximumMessageSizeKB=&quot;2097151&quot;&gt;
    &lt;cacheHosts&gt;
      &lt;add address=&quot;localhost&quot; port=&quot;33333&quot; /&gt;
    &lt;/cacheHosts&gt;
  &lt;/cacheClientSettings&gt;</pre>

It's OK at first and Clients can connect to host without any problems.
But after some(1,2) minutes cache host stuck and begin to throw  the following exception (from log file):

<pre>2015-01-25T11:44:14 WARN Dache Client Disconnected : System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at SimplSockets.SimplSocketServer.ReceiveCallback(IAsyncResult asyncResult) in d:\SimplSockets\SimplSockets\SimplSocketServer.cs:line 473
2015-01-25T11:45:31 WARN Dache Client Disconnected : System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at SimplSockets.SimplSocketServer.ReceiveCallback(IAsyncResult asyncResult) in d:\SimplSockets\SimplSockets\SimplSocketServer.cs:line 473
...</pre>

Above exception happens more in debug mode.
What's wrong?

 StackTrace of clietns:
<pre>[NoCacheHostsAvailableException: There are no reachable cache hosts available. Verify your client settings and ensure that all cache hosts can be successfully communicated with from this client.]
   Dache.Client.CacheClient.DetermineBucket(String cacheKey) in d:\Dache\Dache.Client\CacheClient.cs:947
   Dache.Client.CacheClient.TryGet(String cacheKey, T& value) in d:\Dache\Dache.Client\CacheClient.cs:137
   Smartiz.CacheClient.CacheProvider.TryGet(String key, T& value) in d:\Works\Smartiz\Smartiz.CacheClient\CacheProvider.cs:34
   Smartiz.CacheClient.CachedParams.get_AllAttachmentsTypes() in d:\Works\Smartiz\Smartiz.CacheClient\CacheTools\CachedParams.cs:36
   Smartiz.CacheClient.MappingsProfile.Configure() in d:\Works\Smartiz\Smartiz.CacheClient\Mapper\MappingsProfile.cs:127
   AutoMapper.ConfigurationStore.AddProfile() +56
   Smartiz.CacheClient.AutoMapperConfiguration.<Configure>b__0(IConfiguration x) in d:\Works\Smartiz\Smartiz.CacheClient\Mapper\AutoMapperConfiguration.cs:7
   AutoMapper.Mapper.Initialize(Action`1 action) +41
   Smartiz.CacheClient.AutoMapperConfiguration.Configure() in d:\Works\Smartiz\Smartiz.CacheClient\Mapper\AutoMapperConfiguration.cs:7
   Smartiz.Admin.MvcApplication.Application_Start() in d:\Works\Smartiz\Smartiz.Admin\Global.asax.cs:54

[HttpException (0x80004005): There are no reachable cache hosts available. Verify your client settings and ensure that all cache hosts can be successfully communicated with from this client.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +9916673
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): There are no reachable cache hosts available. Verify your client settings and ensure that all cache hosts can be successfully communicated with from this client.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9930568
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254</pre>

**Comment by ironyx** [comment]
How much data are you sending at one time? I have a theory of what's happening but I want to validate it. Are you sending 5 or 10 megs?

**Comment by Mds92** [comment]
Yes, the data are bigger than 10MB, something like 12MB, 14MB, 18MB, 20MB, ...
less than 50MB
But in future it will be reach to 50MB

**Comment by ironyx** [comment]
Are you sending the 12MB at once, like in a single operation?

**Comment by Mds92** [comment]
Well, I'm using the default methods: `AddOrUpdate` and `TryGet` to send or get big objects.
I thinks all data send with one operation.
In other words:
I'm using `AddOrUpdate` method to send 12 MB data

**Comment by ironyx** [comment]
This is not how distributed caching is intended to be used. It will be slow and not scale. Can you think of a way to distribute this large data into many cache keys? That will help a lot. Problem is timeout is being reached during long send... Client cannot ping server in 10 seconds so it disconnects. Smaller data essential.

**Comment by Mds92** [comment]
Really? I didn't know it.
e.g: 
I wanna cache all user data(id, username, email, name, last name, ...) and re-cache them at create, update, delete. these data are bigger than 12 MB and will grows to ... MB.
When all of user data are cached in a list object with a cache key, I can get the data of an user easily.
But when I cache them with some keys, how should I find the cache key to find the user?

Another question:
How much should be maximum of a cache pack?

**Comment by ironyx** [comment]
There's no rule for size but in general smaller is better. You generally cache by convention. Maybe cache each user data at user cache key like 'user data_#' where '#' is user id? Then it is one object per user instead of list. Also for parts of user data, similar convention but suffix with property names maybe? Gotta bring that size down! Try for 100k or less per cached item.

**Comment by ironyx** [comment]
That was meant to be 'userdata_#' no spaces

**Comment by ironyx** [comment]
Whatever makes the object unique should be part of the key!

**Comment by Mds92** [comment]
Thanks, So I have to change my caching strategy completely :-(

**Comment by ironyx** [comment]
Yes, however know that you're heading for big improvements. This approach and paradigm isn't unique to Dache - it applies to all caching in general. I'm confident you'll like the performance results!
