### ISSUE TITLE
Is it possible to access caches values in dache CacheHost ?

### ISSUE THREAD

**Issue by Mds92** [ironyx/dache#35]
Assume we have a dache's CacheHost on Windows Service.
I wanna do some processes within CacheHost and sending the result (an entity) to the client. (for best performance and minimum data on service channel )

e.g:
Each entity is saved separately in dache cache, like "Device1", "Device2", "Device2", ... (these were cache keys)
I have a method to search a name into all device's entities, so I have to get all caches and check it's name. Now, I'm gonna send a name to dache cache host and get the entity result.

So, my question is:
Is it possible to access cached values in dache cache host?

Sorry, I didn't know where should I post my question!

**Comment by ironyx** [comment]
No, it is not possible. Basically you want to use the right tool for the job. For search I'd recommend Elasticsearch - works very well. For key-value access, Dache works very well. Read here for a little more info also:

https://github.com/ironyx/dache/wiki/Developers-Guide
