### ISSUE TITLE
after restarting service all webapp are unable to reconnect

### ISSUE THREAD

**Issue by ron72no** [ironyx/dache#36]
after restarting the service the log file says that reconnect was successful

03/13/2015 1:17:46 AM
Cache Host Reconnected
The cache client has successfully reconnected to the cache host located at 127.0.0.1:33333

but any cache operation results in the following exception

There are no reachable cache hosts available. Verify your client settings and ensure that all cache hosts can be successfully communicated with from this client.

No other messages from dache logger
Only w3wp restart resolves that issue.

**Comment by ironyx** [comment]
Any repro steps I can take on this?

**Comment by ron72no** [comment]
Hello,

sorry for the delay :)

It's very easy to reproduce. Just create a new asp.net webforms app, instantiate the ClientCache in a static member, put some items into the cache. The cache is running as windows service localhost:33333.

restart the service and try to lookup some items from cache. Sometimes GetAllKeys may work. but all tagged operation results in a disconnect/reconnect.

After recycling the .net IIS worker process, no problems occur :)

Let me provide some suggestions. 

Will it be possible to use more than one cache in the future, like named caches? Currently we simulate this via tagging. No idea, how fast is that ...

What about generic keys? Like native Guid's?

Missing some simple methods, Contains, ContainsTagged, etc.

And, IMO is would be better if the API returns empty IEnumerables instead of null. We use complex LINQ queries! Null results in a crash.

Last but not least, Dache is a very cool lightweight service.

**Comment by ironyx** [comment]
Thanks for input. May make some of this happen. Investigating crash now.

**Comment by Mds92** [comment]
I have the same problem. This problem is happen most of the times in developing.

**Comment by ironyx** [comment]
I've got this nailed down to my communication library, SimplSockets. I will be working it this week to hopefully fix the issue once and for all.

**Comment by Mds92** [comment]
Could you please fix this bug as soon as possible, I'm working on a project used your caching and I can't debug it easily. Because it can't connect to cache service after one debug and I have to stop IIS Express and restart debugging.

**Comment by ironyx** [comment]
Should be fixed in 024abe3a39de06e56d6a97998d0ddc7bddf77632 - please let me know how it goes!
