### ISSUE TITLE
Web App disconnected after some hours?

### ISSUE THREAD

**Issue by Mds92** [ironyx/dache#37]
I'm developing a Web App with Dache, Thanks the author for the fantastic library.
Unfortunately, I have a big problem with it.
In previous version of 1.5.6, it was worse. but in 1.5.6 it's better but still I get The following message:
`There are no reachable cache hosts available. Verify your client settings and ensure that all cache hosts can be successfully communicated with from this client.`
In developing, I get the exception after 2 or 3 times build, and I have to restart cache service and rebuild the application to remove the exception.
In web app after some hours the clients disconnect from cache service. and I have to restart the cache service and web sites to remove the exception.
Could you please guide me, How I can remove this exception?

P.S:
I hosted dache on windows service.

Thanks in advanced

**Comment by 3mehdi** [comment]
I've tested it some days before.
I have the same problem, I think dache is unusable unless this problem solve

**Comment by ironyx** [comment]
I'm working on this now. Sorry for the inconvenience.

**Comment by ironyx** [comment]
I'm making some progress on this. Do either of you @3mehdi or @Mds92 use the `maximumConnections` setting? Can you try setting it to a high number like `10000` and see if that helps? Would help confirm what I think is happening.

**Comment by ironyx** [comment]
1.5.7 is live, and this *should* fix the issue. Please try it and let me know!

**Comment by Mds92** [comment]
Actually, I'm getting the exception in debug mode after 2 or 3 rebuilding(1.5.6) and I didn't use `maximumConnections`.
Unfortunately, I exclude `dache` from my solution because of repetition disconnecting exception, so I can't test it again.
Thanks anyway

**Comment by ironyx** [comment]
Sorry to hear that @Mds92 - I understand as it took me a while to track this one down. If you *do* feel like trying 1.5.7, I'd love to know if the issue remains. It should be solved now.

**Comment by ironyx** [comment]
This is fixed in 1.5.8 for certain. Was a bug where Dache Host could stop accepting new requests when a 0 byte graceful disconnect happened. Sorry about this! Feels damned good to have fixed though - this bug has been plaguing Dache for a few months! Thanks for the help identifying it.
