### ISSUE TITLE
Is it possible to host dache on IIS?

### ISSUE THREAD

**Issue by Mds92** [ironyx/dache#38]
Is it possible to host dache cache on IIS like a WCF service instead of windows service?

**Comment by ironyx** [comment]
Yes, you may host Dache on IIS or in any other process that you'd like (such as a Windows Azure Cloud Service). [See here for details](https://github.com/ironyx/dache/wiki/Quick-Start#host-in-your-own-process)

**Comment by Mds92** [comment]
So, if I host host it on IIS, the communication protocol will be HTTP?
Actually, I wanna change the communication protocol to HTTP to solve 1.5.6 disconnecting problem
