### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by bladefist** [ironyx/dache#40]
I couldn't find this in the wiki:

- Does Dache support expirting cache on it's own? Like an absolute expiration?
- Does it keep a local copy of the cache and sync w/ the server, or does it all come from the host?
- If the host is unreachable, will it work locally? Trying to reduce failure points

Thanks.

**Comment by ironyx** [comment]
Hi, sorry for the delay on the reply!

- Yes, Dache has absolute and relative cache item expiration options
- No, all data comes from host. Having said that, you could easily write a wrapper to do some "local" caching as there are also cache item expiry callbacks built in
- No, but you could again write a wrapper to switch to local cache when the remote cache is unavailable.

Hope this helps, and sorry again for the delay.

-Dave

**Comment by bladefist** [comment]
Thanks!
